### ISSUE TITLE
Does not start on Steam OS 3.3 (bases on Arch Linux)

### ISSUE THREAD

**Issue by Marx1st** [flathub/com.synology.SynologyDrive#23]
It worked fine with 3.2, but now it won't start. No error, nothing.

**Comment by BioIron** [comment]
Same problem here. Reinstalled it twice, but Drive refuses to start no matterwhat i do.
Hope it gets fixed soon.

**Comment by RayJW** [comment]
I do not own a Steam Deck. Could you maybe check if this is still an issue with the newest version and let us know how it goes?

**Comment by BioIron** [comment]
Hi.
This issue was fixed on my Steam Deck after a full factory reset (months ago) that i needed to do for completely unrelated reasons.
To this day, with the latest Steam Deck stable version, Synology Drive works without issues.

Not a... worthy fix in my opinion, but unfortunately, with my issue resolved, i can't help anymore with it.

**Comment by Marx1st** [comment]
> I do not own a Steam Deck. Could you maybe check if this is still an issue with the newest version and let us know how it goes?

Still doesn’t work for me. Had deinstalled it a while ago and reinstalled it now, but won’t start at all.

**Comment by lil5** [comment]
@Marx1st there's a steamdeck iso available now I'll see if I can test it out this week

**Comment by lil5** [comment]
@Marx1st this might be your fix

https://github.com/flathub/com.synology.SynologyDrive/issues/30#issuecomment-1485859352

`rm -r ~/SynologyDrive`

**Comment by Marx1st** [comment]
@lil5 Thanks a lot! Step 2 was actually enough.
